name: release-please
on:
  push:
    branches: [main]
permissions:
  contents: write
  pull-requests: write
  packages: write
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          PGDATABASE: aurora
          POSTGRES_DB: aurora
          POSTGRES_USER: vscode
          POSTGRES_HOSTNAME: localhost
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Run tests with coverage report output
        run: go tool ginkgo -r -coverprofile=coverprofile.out
        env:
          AURORA_DATABASE_URL: "postgres://vscode@localhost:5432/aurora"
      - uses: k1LoW/octocov-action@v1

  release-please:
    runs-on: ubuntu-latest
    needs: [test]
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .github/settings/release-please-config.json
          manifest-file: .github/settings/release-please-manifest.json

  docker:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-buildx-action@v4
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v6
        id: metadata
        with:
          images: ghcr.io/aws-contrib/aws-aurora
          tags: |
            type=semver,pattern={{version}},value=${{ needs.release-please.outputs.tag_name }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.release-please.outputs.tag_name }}
      - uses: docker/build-push-action@v7
        with:
          context: .
          file: ./deployment/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: true
